<?php

namespace Database\Seeders;

use App\Models\Admin\Product;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $products = [
            #home
            [
                'category_id' => 2,
                'name' => 'Kiwi Gold',
                'origin' => 'New Zealand',
                'price' => 27,
                'price_by' => '2',
                'description' => 'Approx 500gm per Pack',
            ],
            [
                'category_id' => 2,
                'name' => 'Figs Fresh',
                'origin' => 'Turkey',
                'price' => 15,
                'price_by' => 2,
                'description' => 'Approx 250gm per pack',
            ],
            [
                'category_id' => 2,
                'name' => 'Coconut Dry',
                'origin' => 'India',
                'price' => 3,
                'price_by' => 1,
                'description' => 'Approx 400gm to 500gm per piece',
            ],
            [
                'category_id' => 2,
                'name' => 'Sweet Melon',
                'origin' => 'Jordan',
                'price' => 10,
                'price_by' => 1,
                'description' => 'Approx 1.8kg to 2kg',
            ],
            [
                'category_id' => 2,
                'name' => 'Peaches',
                'origin' => 'Jordan',
                'price' => 13,
                'price_by' => 2,
                'description' => 'Approx 1kg per Pack',
            ],
            [
                'category_id' => 2,
                'name' => 'Papaya',
                'origin' => 'Thiland',
                'price' => 26,
                'price_by' => 1,
                'description' => 'Approx 500gr to 700gm',
            ],
            [
                'category_id' => 2,
                'name' => 'Kumquats',
                'origin' => 'South Africa',
                'price' => 10,
                'price_by' => 2,
                'description' => 'Approx 250g per Pack',
            ],
            [
                'category_id' => 2,
                'name' => 'Rock Melon',
                'origin' => 'Iran',
                'price' => 10,
                'price_by' => 1,
                'description' => 'Approx 1.7kg to 2kg',
            ],
            [
                'category_id' => 2,
                'name' => 'Prickly Pears',
                'origin' => 'Tunisia',
                'price' => 11,
                'price_by' => 2,
                'description' => 'Approx 500gm per pack',
            ],
            [
                'category_id' => 2,
                'name' => 'Appel Red',
                'origin' => 'South Africa',
                'price' => 9,
                'price_by' => 2,
                'description' => 'Approx 1kg per Pack',
            ],
            [
                'category_id' => 1,
                'name' => 'Marrow Green',
                'origin' => 'Jordan',
                'price' => 6,
                'price_by' => 2,
                'description' => 'Approx 500gm per pack',
            ],
            [
                'category_id' => 1,
                'name' => 'Lettuce Lolo Green Bionda',
                'origin' => 'Netherlands',
                'price' => 13,
                'price_by' => 2,
                'description' => 'Approx 220gm to 250gm',
            ],
            [
                'category_id' => 1,
                'name' => 'Red Cabbage',
                'origin' => 'Iran',
                'price' => 5,
                'price_by' => 2,
                'description' => 'Approx 1kg to 1.2kg',
            ],
            [
                'category_id' => 1,
                'name' => 'cucumber',
                'origin' => 'UAE',
                'price' => 4,
                'price_by' => 2,
                'description' => 'Approx 500gm per pack',
            ],
            [
                'category_id' => 1,
                'name' => 'Garlic Pure White',
                'origin' => 'China',
                'price' => 10,
                'price_by' => 2,
                'description' => 'Approx 1kg per pack',
            ],
            [
                'category_id' => 1,
                'name' => 'Parsley English',
                'origin' => 'Netherlands',
                'price' => 30,
                'price_by' => 3,
                'description' => 'Approx 1kg',
            ],
            [
                'category_id' => 1,
                'name' => 'Red Jalapeno',
                'origin' => 'Netherlands',
                'price' => 99,
                'price_by' => 2,
                'description' => 'aa',
            ],
            [
                'category_id' => 1,
                'name' => 'Potato Chat White',
                'origin' => 'Australia',
                'price' => 22,
                'price_by' => 2,
                'description' => 'Approx 1kg per Pack',
            ],
            [
                'category_id' => 1,
                'name' => 'Tomato Green House',
                'origin' => 'Iran',
                'price' => 34,
                'price_by' => 2,
                'description' => 'Approx 5kg to 5.5kg',
            ],
            [
                'category_id' => 1,
                'name' => 'Pumpkin Red',
                'origin' => 'Iran',
                'price' => 99,
                'price_by' => 1,
                'description' => 'Approx 4kg to 5kg',
            ],
            [
                'category_id' => 1,
                'name' => 'Red Chilli Long',
                'origin' => 'Egypt',
                'price' => 8,
                'price_by' => 2,
                'description' => 'Approx 250gm per pack',
            ],
            [
                'category_id' => 3,
                'name' => 'Pineapple (Cubes)',
                'origin' => 'Philippines',
                'price' => 7,
                'price_by' => 2,
                'description' => 'Approx 250g per pack',
            ],
            [
                'category_id' => 3,
                'name' => 'Honeydew Melon (Cubes)',
                'origin' => 'Australia',
                'price' => 6,
                'price_by' => 2,
                'description' => 'Approx 259g per pack',
            ],
            [
                'category_id' => 3,
                'name' => 'Ginger Chopped',
                'origin' => 'UAE',
                'price' => 4,
                'price_by' => 2,
                'description' => 'Approx 250g per Pack',
            ],
            [
                'category_id' => 3,
                'name' => 'Onion Brown (Peeled)',
                'origin' => 'UAE',
                'price' => 5,
                'price_by' => 2,
                'description' => 'Approx 250 per pack',
            ],
            [
                'category_id' => 3,
                'name' => 'Rock Melon (Cubes)',
                'origin' => 'Brazil',
                'price' => 6,
                'price_by' => 2,
                'description' => 'Approx 200g per pack',
            ],
            [
                'category_id' => 3,
                'name' => 'Red cabbage (Shredded)',
                'origin' => 'Iran',
                'price' => 4,
                'price_by' => 2,
                'description' => 'Approx 250g per pack',
            ],
            [
                'category_id' => 3,
                'name' => 'Cucumber (Sliced)',
                'origin' => 'Jordan',
                'price' => 4,
                'price_by' => 2,
                'description' => 'Approx 250g per pack',
            ],
            [
                'category_id' => 3,
                'name' => 'Carrot (Sticks)',
                'origin' => 'China',
                'price' => 5,
                'price_by' => 2,
                'description' => 'Approx 250g per pack',
            ],
            [
                'category_id' => 3,
                'name' => 'Red Onion (peeled)',
                'origin' => 'Egypt',
                'price' => 4,
                'price_by' => 2,
                'description' => 'Approx 250g per pack',
            ],
            [
                'category_id' => 3,
                'name' => 'Red Onion (Chopped)',
                'origin' => 'Egypt',
                'price' => 4,
                'price_by' => 2,
                'description' => 'Approx 250g per pack',
            ],
            [
                'category_id' => 4,
                'name' => 'Couple Fruit Basket',
                'origin' => 'UAE',
                'price' => 89,
                'price_by' => 1,
                'description' => 'Approx 5kg per basket',
            ],
            [
                'category_id' => 4,
                'name' => 'Family Basket',
                'origin' => 'UAE',
                'price' => 131,
                'price_by' => 1,
                'description' => 'Approx 7kg per basket',
            ],
            [
                'category_id' => 4,
                'name' => 'Mix Fruit Basket Small',
                'origin' => 'UAE',
                'price' => 157,
                'price_by' => 2,
                'description' => 'Approx 10-11 kg',
            ],
            [
                'category_id' => 4,
                'name' => 'Mix Fruit Basket Large',
                'origin' => 'UAE',
                'price' => 210,
                'price_by' => 2,
                'description' => 'Approx 17-18 kg',
            ],
            [
                'category_id' => 4,
                'name' => 'APRICOT PASTE',
                'origin' => 'UAE',
                'price' => 10,
                'price_by' => 2,
                'description' => 'Approx. 400g',
            ],
            [
                'category_id' => 4,
                'name' => 'White Mushroom Baby',
                'origin' => 'UAE',
                'price' => 7,
                'price_by' => 2,
                'description' => 'Approx 250g per pack',
            ],
            [
                'category_id' => 4,
                'name' => 'Salad Pea',
                'origin' => 'Netherlands',
                'price' => 62,
                'price_by' => 2,
                'description' => 'Approx 110g per Pack',
            ],
            [
                'category_id' => 4,
                'name' => 'Rambutan',
                'origin' => 'Thailand',
                'price' => 20,
                'price_by' => 2,
                'description' => 'Approx 500g per pack',
            ],
        ];

        foreach($products as $_item){
            $product = Product::firstOrCreate([
                'name' => $_item['name'],
                'category_id' => $_item['category_id'],
                'origin' => $_item['origin'],
                'price' => $_item['price'],
                'price_by' => $_item['price_by'],
                'description' => $_item['description'],
            ]);
            // echo $permission->name . ' - Done' . PHP_EOL;
        }
    }
}
